cache:
  key: joseswift

before_script:
  - git reset --hard
 
stages:
  - util
  - test
  - upload
  
variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

Test JoseSwiftCommon:
  stage: test
  only:
    - merge_requests
  except:
    - master
  script:
    - fastlane test
  tags:
    - xcode12

Bump Major version:
  stage: util
  when: manual
  script:
    - sh bump.sh -f bump_major -g "git@gitlab.monetplus.cz:ahead_ios/joseswift.git"
  only:
    - master
  tags:
    - xcode12

Bump Minor version:
  stage: util
  when: manual
  script:
    - sh bump.sh -f bump_minor -g "git@gitlab.monetplus.cz:ahead_ios/joseswift.git"
  only:
    - master
  tags:
    - xcode12

Bump Patch version:
  stage: util
  when: manual
  script:
    - sh bump.sh -f bump_patch -g "git@gitlab.monetplus.cz:ahead_ios/joseswift.git"
  only:
    - master
  tags:
    - xcode12

Release to Nexus:
  stage: upload
  when: manual
  script:
    - fastlane ReleaseNexus
  only:
     - master
     - tags
  except:
    - branches
  tags:
    - xcode12